### PR TITLE
Added Nannoq-Tools

### PR DESCRIPTION
**Pull request by mikand13**
Nannoq-Tools is a toolkit for constructing robust, scalable and distributed applications leveraging vertx. Currently geared towards AWS, but planned to be expanded to other cloud services and technologies.

Modules:

- Auth
- Cluster
- FCM (Firebase Cloud Messaging)
- Repository
- Web

Check it out at [Nannoq-Tools](https://noriginmedia.github.io/nannoq-tools/)

### CODE REVIEW

**Comment by michel-kraemer** [comment]
Thanks for the contribution! Looks like an interesting library. However, IMHO we should not add it to the list multiple times. Wouldn't it be possible to add it to a single category only (such as 'Utilities')?

**Comment by mikand13** [comment]
Hey, thought about that too, but ended up with this solution as the only modules directly related are web and repository, and they are all separate artifacts on maven central. 

Im easy tho, what's the usual approach for this in the repo?

**Comment by michel-kraemer** [comment]
AFAICT, we've never had such a case. Or - which is more likely - people just added their library to a single category.

**Comment by mikand13** [comment]
Hmm, could link to the individual modules documentation e.g. /nannoq-tools/fcm instead of the root. Will be an implicit connection through the name, but separates the functionality.

**Comment by michel-kraemer** [comment]
Thanks for the update. However, linking to different documentation pages doesn't help. Sorry. It's still one library. Please add only one entry and give it a reasonable description (Something like: "Nannoq-Tools is a toolkit for constructing robust, scalable and distributed applications leveraging Vert.x including modules for authentication, cluster management, Firebase Cloud Messaging, etc."). Even then your description will be much longer than most of the others. :)

**Comment by mikand13** [comment]
No problem, how about this? :)

**Comment by michel-kraemer** [comment]
Thanks a lot!! :) :+1:

**Pull request merged**
