### PR TITLE
Added crabzilla

### PR DESCRIPTION
**Pull request by rodolfodpk**
I'd like to add my pet project to vertx-awesome. 

Thanks,
Rodolfo

### CODE REVIEW

**Comment by pmlopes** [comment]
@rodolfodpk why not release the jars to maven central? in that case it is easier to get started and users do not need to build from source.

**Comment by rodolfodpk** [comment]
@pmlopes I do agree. But I still need to finish some key features like the support for process managers (sagas), write a road map, a getting started, more unit tests, samples, docs, etc. I would like to have it all done before publishing it to maven central. I will inform you guys when I finally accomplish the release, thanks.

**Comment by rodolfodpk** [comment]
I just published it to Maven Central : https://repo.maven.apache.org/maven2/io/github/crabzilla/
:)

**Comment by pmlopes** [comment]
Thanks

**Pull request merged**
