### PR TITLE
Command line client for vertx bus 

### PR DESCRIPTION
**Pull request by cinterloper**
window 1:
```
$ echo '{"this":"that"}' | vxc -n callback

```
window 2:

```
$ vxc -n callback -l
{"this":"that"}
```

### CODE REVIEW

**Comment by michel-kraemer** [comment]
* Please fix the merge conflict
* Add a dot at the end of the description
* Use consistent spelling of "Vert.x"
* I'd prefer "Command line binary client" to be "Command-line binary client"
* and "json" to be "JSON"

Sorry for the nitpicking, but all of this improves our chance to be included in the list of awesome lists:
https://github.com/sindresorhus/awesome

**Comment by michel-kraemer** [comment]
Oh, and don't remove the empty line please.

**Comment by cinterloper** [comment]
Ok, I believe I have make the proposed updates.

**Comment by michel-kraemer** [comment]
👍

**Comment by cescoffier** [comment]
Thanks !

**Pull request merged**
