### PR TITLE
vertx-s3-client

### PR DESCRIPTION
**Pull request by eemmiirr**
A fully functional Vert.x client for S3

### CODE REVIEW

**Comment by pmlopes** [comment]
@eemmiirr would you mind to add a final `.` to the sentence, like we have on all other entries.

**Comment by eemmiirr** [comment]
Done. Sorry didn't even notice there is a .

**Comment by michel-kraemer** [comment]
Thanks for the pull request. It's a very nice project indeed, but I'm not sure if `NoSQL Databases` or `Database clients` is the right category. S3 is no database.

Any ideas where it would fit better? Should we create a new category for 'Object Stores' or 'Cloud Integration' (there already is a 'Cloud Support' category) or something like that?

**Comment by eemmiirr** [comment]
yes i think 'Cloud Support' would fit

**Comment by michel-kraemer** [comment]
OK. I moved it to 'Cloud Support'. If someone has a better idea or if new similar libraries are added that require a new section we can still change it.

**Pull request merged**
