### PR TITLE
add hystrix-vertx-metrics-stream

### PR DESCRIPTION
**Pull request by kennedyoliveira**
Hello!

I did a implementation,[hystrix-vertx-metrics-steram](https://github.com/kennedyoliveira/hystrix-vertx-metrics-stream), to add the metrics publishing to a vertx application that uses [Netflix Hystrix](https://github.com/Netflix/Hystrix).

### CODE REVIEW

**Comment by cescoffier** [comment]
Why did you create a Hystrix "kind" of category ?

**Comment by kennedyoliveira** [comment]
I followed the Meteor example, if it's not suitable i can change.

**Comment by cescoffier** [comment]
You are right ! I gonna merge your PR and to some re-org.

**Comment by kennedyoliveira** [comment]
@cescoffier, thank you, i'm glad to help! :D

**Pull request merged**
