### PR TITLE
Modify Zookeeper cluster manger location

### PR DESCRIPTION
**Pull request by stream1984**
Modify Zookeeper cluster manger location

### CODE REVIEW

**Comment by michel-kraemer** [comment]
+1

I suppose we'll wait until 3.4.0 is released? Or can we merge it now?

**Comment by vietj** [comment]
there is a current release deployed in central for 3.3.3 but it is not yet on the web-site

**Comment by stream1984** [comment]
Maybe merge this PR after web-site 3.4.0 release with this [PR](https://github.com/vert-x3/vertx-web-site/pull/197)

**Comment by vietj** [comment]
the 3.4.0-release website will be merged just at 3.4.0 release time

**Comment by vietj** [comment]
and I cherry-picked your change @stream1984 in the 3.4.0-release branch

**Pull request merged**
