### PR TITLE
Added Microservices section with standard Vert.x modules

### PR DESCRIPTION
**Pull request by aschrijver**
The latest addition of microservices modules released in 3.3.0 were not there yet....so here they are :)
In the next PR I would like to add this repo to this section: https://github.com/engagingspaces/vertx-graphql-service-discovery

### CODE REVIEW

**Comment by aschrijver** [comment]
Pfff, it's still early Saturday morning. Got the names wrong. Luckily easily fixed..

**Comment by michel-kraemer** [comment]
Looks good to me. Thanks!

Two nitpicks:
* I'm not sure if we need the same link five times. Someone from the core team should decide.
* Don't forget to update the toc if you add a new section.

**Comment by aschrijver** [comment]
I'll add that to the ToC.
I added the link 5 times, because I thought it relevant to show the integrations that are available by default in this awesome list. For many people this awesome list may be the first contact they have with Vert.x.

**Comment by cescoffier** [comment]
Thanks !

**Pull request merged**
